name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
        
      - name: Build each feature
        run: cargo hack build --verbose --each-feature
      - name: Run tests each feature
        run: cargo hack test --verbose --each-feature

      - name: Build all features
        run: cargo hack build --verbose --all-features
      - name: Run tests all features
        run: cargo hack test --verbose --all-features

      - name: Build feature-powerset
        run: cargo hack build --verbose --feature-powerset
      - name: Run tests feature-powerset
        run: cargo hack test --verbose --feature-powerset
